Algoritmo "questão 2"
// Construa um algoritmo em PORTUGOL que leia dois valores numéricos inteiros e
//efetue a adição; caso o resultado seja maior que 10, apresentá-lo.
Var
   n1,n2,sm :inteiro
Inicio
   escreva("informe o primeiro número  inteiro:")
   leia(n1)
   escreva("informe o segundo número inteiro:")
   leia(n2)
   sm<- n1+n2
   se sm>10 entao
      escreva("",sm,"")
   fimse
Fimalgoritmo
